DROP TABLE IF EXISTS doc;

CREATE TABLE doc (
	code TEXT NOT NULL PRIMARY KEY,
	libelle TEXT NOT NULL,
	lien TEXT,
	etiquette TEXT,
    creation TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    maj TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS user;

CREATE TABLE user (
	idUser TEXT NOT NULL PRIMARY KEY,
	nom TEXT NOT NULL,
	prenom TEXT NOT NULL,
	mail TEXT,
    droit INT NOT NULL DEFAULT 0
);
